// Generated by backend/scripts/upload-public-assets.mjs
export const cloudinaryAssets = {
  "about-hero.png": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215097/nestro/static/about-hero.jpg",
  "dining-set.png": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215099/nestro/static/dining-set.jpg",
  "file.svg": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215100/nestro/static/file.svg",
  "globe.svg": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215101/nestro/static/globe.svg",
  "next.svg": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215103/nestro/static/next.svg",
  "sofa.png": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215106/nestro/static/sofa.jpg",
  "vercel.svg": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215107/nestro/static/vercel.svg",
  "window.svg": "https://res.cloudinary.com/dhvkipcza/image/upload/v1787215110/nestro/static/window.svg"
};
