export const MOCK_PRODUCTS = [
  {
    _id: "p-1",
    name: "Classic Velvet Chesterfield Sofa",
    categoryId: { name: "SOFAS", slug: "sofas" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 86400,
    originalPrice: 108000,
    discount: 20,
    rating: 5,
    reviewsCount: 16,
    material: "Velvet",
    color: "Dark Brown/Charcoal",
    stock: true,
    slug: "classic-velvet-chesterfield-sofa",
    shortDescription: "A timeless masterpiece featuring tufted velvet upholstery and elegant rolled arms. Hand-crafted to bring classical comfort to modern spaces.",
    description: "The Classic Velvet Chesterfield Sofa represents the ultimate in heritage style. Deep button-tufting details accent its luxurious velvet exterior, while dense polyurethane foam padding ensures structural integrity and comfort that lasts. Framed with robust, solid hardwood rails and accented by beautifully turned oak feet.",
    dimensions: { width: 220, height: 78, depth: 95 },
    weight: 62
  },
  {
    _id: "p-2",
    name: "Scandinavian 3-Seater Sofa",
    categoryId: { name: "SOFAS", slug: "sofas" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 57000,
    originalPrice: 68400,
    discount: 17,
    rating: 4.8,
    reviewsCount: 79,
    material: "Linen",
    color: "Slate Blue",
    stock: true,
    slug: "scandinavian-3-seater-sofa",
    shortDescription: "Minimalist aesthetic meets exceptional everyday comfort. Upholstered in premium linen-blend fabric with natural wood legs.",
    description: "Embrace nordic clean lines and functional design. This Scandinavian 3-Seater features high-resilience foam seat cushions wrapped in heavy-duty weave polyester-linen fabric. Solid oak legs lend stability and height, making it visually light and extremely practical.",
    dimensions: { width: 205, height: 82, depth: 88 },
    weight: 48
  },
  {
    _id: "p-3",
    name: "Luxury Leather L-Shape Sectional",
    categoryId: { name: "SOFAS", slug: "sofas" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 216000,
    originalPrice: 256000,
    discount: 16,
    rating: 4.9,
    reviewsCount: 86,
    material: "Leather",
    color: "Dark Brown/Charcoal",
    stock: true,
    slug: "luxury-leather-l-shape-sectional",
    shortDescription: "Expansive sectional sofa wrapped in top-grain aniline leather. Configured with a left-facing chaise for optimal relaxation.",
    description: "Make a statement with the Luxury Leather Sectional. Hand-stitched with top-grain Italian leather, this L-shape sectional develops a beautiful unique patina over time. High-density pocket spring cores guarantee supportive seating, while steel-reinforced frames provide long-term performance.",
    dimensions: { width: 310, height: 80, depth: 165 },
    weight: 110
  },
  {
    _id: "p-4",
    name: "Ember Velvet 3-Seater",
    categoryId: { name: "SOFAS & SECTIONALS", slug: "sofas" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 89000,
    originalPrice: 108000,
    discount: 18,
    badge: "BESTSELLER",
    rating: 5,
    reviewsCount: 48,
    material: "Velvet",
    color: "Dark Brown/Charcoal",
    stock: true,
    slug: "ember-velvet-3-seater",
    shortDescription: "Sultry velvet curves wrapped around a kiln-dried eucalyptus framework. Perfectly proportioned for dynamic living spaces.",
    description: "Deep, comfortable seating designed with premium velvet fabric. The Ember Velvet 3-Seater is structured for optimal seating ergonomics, incorporating sinuous spring suspension beneath thick plush cushions.",
    dimensions: { width: 215, height: 80, depth: 90 },
    weight: 54
  },
  {
    _id: "p-5",
    name: "Natura Dining Table",
    categoryId: { name: "DINING", slug: "dining" },
    roomId: { name: "Dining Room", slug: "dining-room" },
    salePrice: 124000,
    originalPrice: 155000,
    discount: 20,
    rating: 5,
    reviewsCount: 62,
    material: "Solid Wood",
    color: "Medium Brown",
    stock: true,
    slug: "natura-dining-table",
    shortDescription: "Stunning solid wood dining table showing off beautiful organic grain flows. Comfortably seats up to 8 guests.",
    description: "Crafted from seasoned solid walnut wood, the Natura Dining Table highlights the natural character of timber with knots and unique grain structures. Protected with a hardwearing matte polyurethane topcoat to endure daily spills.",
    dimensions: { width: 200, height: 76, depth: 95 },
    weight: 75
  },
  {
    _id: "p-6",
    name: "Terra Coffee Table",
    categoryId: { name: "TABLES", slug: "tables" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 38000,
    discount: 0,
    badge: "NEW",
    rating: 4.2,
    reviewsCount: 29,
    material: "Marble",
    color: "Off-white/Cream",
    stock: true,
    slug: "terra-coffee-table",
    shortDescription: "Sculptural round coffee table with an authentic white marble top slab and a fluted wooden base.",
    description: "An elegant centerpiece for any living layout. The polished white Carrara marble top boasts natural grey veining, resting securely on a handcrafted fluted oak veneer column.",
    dimensions: { width: 90, height: 40, depth: 90 },
    weight: 40
  },
  {
    _id: "p-7",
    name: "Aura Bouclé Armchair",
    categoryId: { name: "ACCENT CHAIRS", slug: "chairs" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 54000,
    discount: 0,
    badge: "BESTSELLER",
    rating: 4.9,
    reviewsCount: 94,
    material: "Linen",
    color: "Slate Blue",
    stock: true,
    slug: "aura-boucle-armchair",
    shortDescription: "Cozy armchair wrapped in premium textured bouclé-style linen. Features a modern organic swivel silhouette.",
    description: "Wrap yourself in absolute comfort. The Aura features a fully cushioned wrap-around backrest with a solid wood swivel platform underneath, allowing 360-degree rotation.",
    dimensions: { width: 85, height: 75, depth: 80 },
    weight: 24
  },
  {
    _id: "p-8",
    name: "Walnut Media Console",
    categoryId: { name: "MEDIA & TV UNITS", slug: "media" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 67000,
    originalPrice: 86000,
    discount: 22,
    rating: 4.5,
    reviewsCount: 37,
    material: "Solid Wood",
    color: "Dark Brown/Charcoal",
    stock: true,
    slug: "walnut-media-console",
    shortDescription: "Mid-century inspired media storage console. Engineered with slatted sliding doors and wire management ports.",
    description: "Clean design meets home entertainment storage. Constructed using American walnut veneer, this console offers spacious cabinets, soft-close drawers, and adjustable internal shelves.",
    dimensions: { width: 180, height: 55, depth: 45 },
    weight: 52
  },
  {
    _id: "p-9",
    name: "Linen Wardrobe Cabinet",
    categoryId: { name: "BEDROOM", slug: "bedroom" },
    roomId: { name: "Bedroom", slug: "bedroom" },
    salePrice: 118000,
    discount: 0,
    badge: "NEW",
    rating: 5,
    reviewsCount: 19,
    material: "Linen",
    color: "Sand",
    stock: false,
    slug: "linen-wardrobe-cabinet",
    shortDescription: "Elegant wardrobe wrapped in soft linen weave panels. Integrated with brass accents and interior lighting.",
    description: "A gorgeous freestanding storage unit. Features dual linen-upholstered doors opening to reveal hanging rails, built-in dresser drawers, and high-quality brass pulls.",
    dimensions: { width: 120, height: 200, depth: 60 },
    weight: 88
  },
  {
    _id: "p-10",
    name: "Mid-Century Modern Loveseat",
    categoryId: { name: "SOFAS", slug: "sofas" },
    roomId: { name: "Living Room", slug: "living-room" },
    salePrice: 50316,
    originalPrice: 63000,
    discount: 20,
    rating: 4.7,
    reviewsCount: 15,
    material: "Velvet",
    color: "Sand",
    stock: true,
    slug: "mid-century-modern-loveseat",
    shortDescription: "Charming two-seater sofa perfect for compact spaces. Retro flared wooden peg legs and button-tufted backrest.",
    description: "Vintage aesthetics paired with modern performance materials. Dense foam padding wrapped in durable sand-coloured velvet fabric stands up to high-traffic utility while remaining soft.",
    dimensions: { width: 160, height: 80, depth: 85 },
    weight: 38
  },
  {
    _id: "p-11",
    name: "Platform King Bed with Headboard",
    categoryId: { name: "BEDS", slug: "beds" },
    roomId: { name: "Bedroom", slug: "bedroom" },
    salePrice: 79112,
    originalPrice: 96000,
    discount: 20,
    rating: 5,
    reviewsCount: 39,
    material: "Solid Wood",
    color: "Sand",
    stock: true,
    slug: "platform-king-bed-with-headboard",
    shortDescription: "Minimalist oak frame platform bed featuring a woven upholstered panel headboard.",
    description: "Bring earthy warmth to the master bedroom. Built from selected light oak wood with a sturdy slats system that eliminates the need for box springs. Features a padded linen headboard.",
    dimensions: { width: 210, height: 110, depth: 220 },
    weight: 80
  },
  {
    _id: "p-12",
    name: "Tufted Velvet Storage Queen Bed",
    categoryId: { name: "BEDS", slug: "beds" },
    roomId: { name: "Bedroom", slug: "bedroom" },
    salePrice: 79128,
    originalPrice: 97200,
    discount: 20,
    rating: 4.8,
    reviewsCount: 27,
    material: "Velvet",
    color: "Slate Blue",
    stock: true,
    slug: "tufted-velvet-storage-queen-bed",
    shortDescription: "Elegant velvet upholstered bed featuring an easy-lift hydraulic storage container underneath.",
    description: "Luxurious style and intelligent utility combined. The gas-lift hydraulic system raises the mattress deck seamlessly to reveal large storage compartments for blankets and out-of-season wear.",
    dimensions: { width: 170, height: 125, depth: 215 },
    weight: 95
  },
  {
    _id: "p-13",
    name: "Minimalist Oak Desk",
    categoryId: { name: "TABLES", slug: "tables" },
    roomId: { name: "Home Office", slug: "home-office" },
    salePrice: 24500,
    discount: 0,
    rating: 4.3,
    reviewsCount: 12,
    material: "Solid Wood",
    color: "Sand",
    stock: true,
    slug: "minimalist-oak-desk",
    shortDescription: "Clean home office writing desk. Includes two slim drawer compartments and integrated cord management.",
    description: "Design simplicity to help organize your focus. Formed with solid oak wood legs and oak veneers, offering a durable work surface for laptops and notebooks.",
    dimensions: { width: 120, height: 75, depth: 60 },
    weight: 28
  },
  {
    _id: "p-14",
    name: "Leather Office Chair",
    categoryId: { name: "ACCENT CHAIRS", slug: "chairs" },
    roomId: { name: "Home Office", slug: "home-office" },
    salePrice: 18900,
    discount: 0,
    badge: "NEW",
    rating: 4.6,
    reviewsCount: 22,
    material: "Leather",
    color: "Dark Slate/Black",
    stock: true,
    slug: "leather-office-chair",
    shortDescription: "Classic adjustable swivel desk chair upholstered in supple brown distressed leather.",
    description: "Ergonomic support meeting retro mid-century executive design. Height adjustable pneumatic base with chrome legs and smooth rolling caster wheels.",
    dimensions: { width: 65, height: 95, depth: 65 },
    weight: 16
  },
  {
    _id: "p-15",
    name: "Glass Display Cabinet",
    categoryId: { name: "STORAGE", slug: "storage" },
    roomId: { name: "Dining Room", slug: "dining-room" },
    salePrice: 58000,
    discount: 0,
    badge: "NEW",
    rating: 5,
    reviewsCount: 14,
    material: "Solid Wood",
    color: "Dark Slate/Black",
    stock: true,
    slug: "glass-display-cabinet",
    shortDescription: "Magnificent dining showcase unit with tempered glass windows and solid oak wood frame.",
    description: "Display fine dinnerware or precious collectibles. The premium dark charcoal cabinet houses 4 glass shelves backed by an optional ambient warm LED strip system.",
    dimensions: { width: 90, height: 185, depth: 40 },
    weight: 70
  }
];

export const colorSwatches = [
  { name: "Off-white/Cream", value: "#FAF7F2", borderClass: "border-gray-300" },
  { name: "Dark Slate/Black", value: "#2C1C18", borderClass: "border-transparent" },
  { name: "Medium Brown", value: "#8C6239", borderClass: "border-transparent" },
  { name: "Slate Blue", value: "#6A7D8C", borderClass: "border-transparent" },
  { name: "Sand", value: "#D6C5B3", borderClass: "border-transparent" },
  { name: "Dark Brown/Charcoal", value: "#3E2A24", borderClass: "border-transparent" }
];

export const materialsList = ["Solid Wood", "Velvet", "Linen", "Marble", "Leather"];
export const roomFallback = ["Living Room", "Bedroom", "Dining Room", "Home Office"];
